name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    env:
    XCODE_VERSION: "14.2"

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: xcode-select -switch "/Applications/Xcode_${XCODE_VERSION}.app"

    - name: Build and Test
      run: xcodebuild clean build test -project POC_CustomizeYourOrder/POC_CustomizeYourOrder.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO